restClient:
  movieInfoUrl: localhost:8082
  reviewUrl: localhost:8083
spring:
  profiles:
    active: local
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/?authSource=admin&retryWrites=true&w=majority